### ISSUE TITLE
UUID Migration failed 

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#105]
I get the following message on startup: "Disabling UUIDs is not recommended and can lead to unexpected behaviour. Please consider enabling UUIDs. The option will be removed with v2.1."

For this reason I tried to change the following settings in the config:
UseUUIDs: false -> true
UseUUIDSeparators: false -> true

However, the migration does not work and the corresponding player data is not loaded. Is there any way I can migrate to UUID usage?
Error: https://pastebin.com/YLGzRD03

MarriageMaster 2.0.18
paper 1.13.2 - 652

**Comment by GeorgH93** [comment]
Please add [this](https://ci.pcgamingfreaks.at/job/PluginLib/326/artifact/target/PluginLib-1.0.18-SNAPSHOT.jar) to your plugins folder and try again.
It will probably fail again, bug should now print a more detailed message about what went wrong (look for "Mojang responded with status code: 400" in the log).

**Comment by TheoRetisch1** [comment]
Thank you for the quick reply! Here is the new error: https://pastebin.com/WfNc7rCg

**Comment by GeorgH93** [comment]
Thanks for the report. Looks like Mojang has reduced how many profiles can be resolved with one API call. I have changed the code to automatically use the limit that the API reports back.
Please add [this](https://ci.pcgamingfreaks.at/job/PluginLib/327/artifact/target/PluginLib-1.0.18-SNAPSHOT.jar) to your plugins folder and try again.

**Comment by TheoRetisch1** [comment]
Thank you fo your help! Unfortunatly I get this error now: https://pastebin.com/QLuTuUxR

**Comment by GeorgH93** [comment]
Thanks for the report. Should be fixed with this build: https://ci.pcgamingfreaks.at/job/PluginLib/333/artifact/target/PluginLib-1.0.18-SNAPSHOT.jar

**Comment by TheoRetisch1** [comment]
Unfortunatly it doesn't work I keep getting this errors :/
https://pastebin.com/7uqfxZP7

**Comment by GeorgH93** [comment]
Is your server running in offline mode? (If you are using BungeeCord is it running in offline mode?) Are you using MySQL or SQLite?

**Comment by TheoRetisch1** [comment]
Thanks for not giving up xD! The server runs in online mode.  I don't use BungeeCord. At the moment I use SQLite. But a Mysql database is available, so I could switch if the migration is possible and necessary. My current config looks like this:
https://pastebin.com/xwHkS7xM

**Comment by GeorgH93** [comment]
I don't know how many players are in your database in total and how old it is, but I would assume that the failing players have renamed them self some time ago (> 30 days), if they have since joint the server they would already be in the table with their new names and if not they will probably not care if their marriage is lost.
If you think that might be the case I would recommend you to stop the server and open the database.db file with DB Browser for SQLite, go to the Execute SQL tab, run that command `DELETE from marry_players where uuid=NULL;`, click write changes and start the server again. This will remove all players without an UUID from the database.

If you do not think that this might be the problem, could you provide me the database file, so that I can take a look at this?

**Comment by TheoRetisch1** [comment]
I can't find an option to see when the database was created, but I estimate end 2014 to mid 2015. 507 players are in the database, many of them have not received a uuid. Your assumptions are correct, the partners will be separated after three months of absence anyway. 
Here is the database:
https://www.mediafire.com/file/lboqdhoui0nf8le/database.db/file

Your script works, if one adapts it a little:
`DELETE FROM marry_players where uuid is NULL;`

I'll test it later on the main server and let you know. Thanks a lot already!

**Comment by TheoRetisch1** [comment]
It worked 💯  Thanks for your patience!
