### ISSUE TITLE
Player Offline when trying to marry cross mode with Bungeecord support on

### ISSUE THREAD

**Issue by Skizzles** [GeorgH93/MarriageMaster#150]
### Information
**Environment information**
*Plugin + server version info*:

```
[02:59:13 INFO]: ##### Start Marriage Master version info #####
[02:59:13 INFO]: Marriage Master: 2.2.1-Release
[02:59:13 INFO]: Server: git-Paper-375 (MC: 1.15.2)
[02:59:13 INFO]: Java: 1.8.0_242
[02:59:13 INFO]: MVdWPlaceholderAPI: 3.1.1
[02:59:13 INFO]: PlaceholderAPI: 2.10.6
[02:59:13 INFO]: ##### End Marriage Master version info #####
```

*Online mode*: yes

*BungeeCord*: yes

**Server/crash log**

```
No crash/errors to report, only 
[03:00:27 INFO]: "playername" is offline!
```

**Plugin config (optional)**

```
https://gist.github.com/Skizzles/d48a184b1b8d80a0d183a460c89171cc
```

### Details
**Description**  
States player is offline when trying to marry cross mode

**Steps to reproduce**  
attempted to marry across mode

**Expected behavior**  
Would expect it to allow marry across mode when bungeecord support is enabled

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)
I would allow players to marry across mode with bungeecord support, this would give a more integrated feeling to the plugin.

**Comment by GeorgH93** [comment]
Both players have to be on the same server in order to get married.

If you have installed the plugin on all your servers (including the BungeeCord), have set the same database to all of them and enabled the config option the following features will work cross server: chat, tp, home
I am sorry, but I currently don't have enough time to add more cross server integrations.
