### ISSUE TITLE
/marry home No permission error

### ISSUE THREAD

**Issue by jiajunmao** [GeorgH93/MarriageMaster#187]
Bungee Cord + 1.16.4 Paper. LuckPerm permission plugin. Using standalone mode.

No one on the server can execute /marry home command(including OP). All other /marry commands are functioning normally. /marry tp works cross server. Default group has marry.user permission node. Furthermore, /marry sethome/delhome works fine.

It is weird because the error message it throws is "You have no permission to do this", which is not a string that I can find in the marriage master source code, and is not the error we throw from LuckPerm if someone has no permission. 

There is also no logging at all in the console, both for the paper and the bungee server.

**Comment by jiajunmao** [comment]
Also tried with explicitly giving marry.home perm node. Still shows "You have no permission to do this"

**Comment by GeorgH93** [comment]
Assuming you have not changed the message in your language file (`NoPermission` node, default is `You don't have the permission to do that.`), I would say that some other plugin is causing this.
Since the home command is handled on the BungeeCord server (at least most of it) my guess would be that it is some plugin there.
There are currently no events defined in the BungeeCord API of MarriageMaster, so what ever is causing it would have to check the executed command string.
You could try to add an alias for the home command in the language file (on the BungeeCord) by adding another entry to the `Command.Home` list and check if that command works.

**Comment by jiajunmao** [comment]
Ok will try and report back. Thanks for the help!

**Comment by jiajunmao** [comment]
Aliasing to some other command solved the issue. Will keep investigating what's causing the problem. But thank you so much for pointing the direction! Will close the issue.
