### ISSUE TITLE
Marry gift doesn't work

### ISSUE THREAD

**Issue by TheoRetisch1** [GeorgH93/MarriageMaster#199]
### Information
**Environment information**
*Plugin + server version info*:
```
##### Start Marriage Master version info #####
Marriage Master: 2.4-RC4-T20210604150658
PCGF PluginLib: 1.0.33-SNAPSHOT-T20210613134940
Server: git-Paper-762 (MC: 1.16.5)
Java: 1.8.0_231
PlaceholderAPI: 2.10.10-DEV-123
#####  End Marriage Master version info  #####
```

*Online mode*: yes
*BungeeCord*: no

**Server/crash log**
```
no errors
```

**Plugin config (optional)**
```
https://gist.github.com/TheoRetisch1/2d98053ac841c55e682efbfcb58605f9
```

### Details
**Description**  
It is not possible to use `/marry gift` in any game mode. The GameModeNotAllowedSender message always appears. Granting all marriage master permissions, granting OP permissions and trying out all game modes doesn't change this result.

**Steps to reproduce**  
Enter /marry gift in gamemode 0.

**Expected behavior**  
Gift Items to your partner.

**Comment by GeorgH93** [comment]
Should be fixed in the newest [release build](https://ci.pcgamingfreaks.at/job/MarriageMaster/289/artifact/artifacts/MarriageMaster-2.4-Release.jar).

**Comment by ItsMeBlaze** [comment]
i have this plugin installed just now since i update my server to 1.17 yesterday and i got your new release build first thing and my gifting says:  Your partner can not receive gifts in it's current current game mode.  what does this mean i even renewed the config file with the one on the github page of the config that i shouldnt change just to be sure when the partner gets set in specator or creative or even adventure lets say any other then the gamemode the other is in and it works but not when in same gamemode any help on this since i cant figure it out.

**Comment by GeorgH93** [comment]
Should be fixed with [this release](https://github.com/GeorgH93/MarriageMaster/releases/tag/v2.4.1).

**Comment by ItsMeBlaze** [comment]
yes this fix fixed it it works now :D
