### ISSUE TITLE
Manually Adding tp home chat Permissions Doesn't Work

### ISSUE THREAD

**Issue by jahua50** [GeorgH93/MarriageMaster#219]
### Information
**Environment information**
*Plugin + server version info*:
2.4.2 + 1.17.1 paper
```

![image](https://user-images.githubusercontent.com/35772634/130576053-b2ded188-3bcb-4ca6-bbf1-a1ffcbc7301d.png)

```

*Online mode*: Yes

*BungeeCord*: Yes

**Server/crash log**
No crash log nor console outputs
```


```

**Plugin config (optional)**
I use mysql for both luckperms and marriage master. They all use the same database (remotely).
```


```

### Details
**Description**  
After adding marry.tp, marry.home, marry.chat, marry.chat.format, marry.chat.color 
permission nodes to both bungee server and the backend server, it still shows that 
"you don't have permission to do that"
OP can access to those commands, but not the players.
Non-OP players with marry.* also can't access those commands either.

Btw, I use luckperms and set the bungee server's setting as "server=bungee", and set the backend server's settings as "server=global"
![image](https://user-images.githubusercontent.com/35772634/130576499-773e650b-7b60-4647-984b-433091b948bf.png)

**Steps to reproduce**  

**Expected behavior**  

**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
I have never used luckperms with BungeeCord, but I just tested it with a very simple YAML backed setup and it worked without issues after adding the permissions.
Could you please export your permissions (`/lb export --upload --without-users`) and share them with me, so that I can have a look at it?
Also you could try to add the permissions to the default group in the BungeeCord config.
