### ISSUE TITLE
Cannot use Chinese name

### ISSUE THREAD

**Issue by zfms4188** [GeorgH93/MarriageMaster#222]
### Information
**Environment information**
*Plugin + server version info*:

```

Marriage Master: 2.4.2-Release + 1.7.10 uranium

```

*Online mode*: BungeeCord online mode

*BungeeCord*: yes 

**Server/crash log**

```

```

**Plugin config (optional)**

```

```

### Details
**Description**  
 Players with Chinese names cannot use commands such as marriage.
 After the command is executed, the following information is displayed: "null is offline!"
**Steps to reproduce**  
 /marry marry 小明
**Expected behavior**  
Let plu-ins support Chinese names  XD
**Other information** (e.g. detailed explanation, related issues, suggestions how to fix, links for us to have context, screenshots, etc.)

**Comment by GeorgH93** [comment]
This most likely is an issue with uranium not handling characters that are not valid Minecraft usernames correctly when accessing getting the offline player from the players name.

If your server is running offline mode I would recommend you to filter the user name to only contain these characters `a-zA-Z0-9_-` (only these characters where valid in usernames back in the 1.7 days). There are many things that break in these old Minecraft versions when you allow usernames with other characters. You can then use a plugin that allows to change the display name to get back Chinese names.

I'm sorry, due to the age of Minecraft 1.7 and the high amount of work for a workaround, I decided to not fix this.
