### ISSUE TITLE
Further support for Poly Marriages

### ISSUE THREAD

**Issue by LadyHaley** [GeorgH93/MarriageMaster#97]
### Feature request
Further support for Poly Marriages
**Feature description**

From what I can tell, the following commands dont play to well when a player has more than one partner.
/marry backpack
/marry chat
/marry tp
/marry home
/marry gift
/marry kiss

Could you please add an optional username tag that is required when a player is married to more than one player.
**How the feature is useful**

Players can use /marry chat for example to talk to one partner because it currently sends it to all partners, which can be confusing when replying to a msg from one partner but not another, similar thing with the other commands. Im sure im missing some commands that were not featured on the plugin page but you get the picture

**Comment by GeorgH93** [comment]
If no partner is explicitly selected it should take the nearest one (except for chat, there the default is to all (thou that might not be a good default if I think about it :D)).
`/marry backpack <partner name>` should work and be shown in help if the player has more than one partner
`/marry chat target <partner name>` should allow to change the target of the private chat
`/marry tp <partner name>` should work, thou I think the help will not inform players that that is an option (will check it later, if it is indeed missing it will be added with v2.1)
`/marry home <partner name>` should work, also possible that the help is not indicating it as an option (will check it later, if it is indeed missing it will be added with v2.1)
`/marry gift <partner name>` should work, also possible that the help is not indicating it as an option (will check it later, if it is indeed missing it will be added with v2.1)
`/marry kiss <partner name>` should work, will not be indicated by help (and I do not plan on adding it), because of the usually operating radius
and for any missing they most likely also have the <partner name> option, but it might be missing from the help list. I will do some command handling rework with the v2.1 update that should make it a bit more uniform
